# Generated by Django 5.1.8 on 2025-04-27 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseYacht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builder', models.CharField(blank=True, max_length=50, null=True)),
                ('model_name', models.CharField(blank=True, max_length=50, null=True)),
                ('model_number', models.CharField(blank=True, max_length=50, null=True)),
                ('variant', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RigType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Mast-Head Sloop', 'mast-head sloop'), ('Fractional Sloop', 'fractional sloop'), ('Sloop', 'Sloop'), ('Ketch', 'Ketch'), ('Cutter', 'Cutter'), ('Yawl', 'Yawl'), ('Catamaran', 'Catamaran'), ('Trimaran', 'Trimaran')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('main', 'Main Mast'), ('mizzen', 'Mizzen Mast'), ('fore', 'Foremast'), ('aft', 'Aft Mast')], default='main', max_length=20)),
                ('i', models.FloatField(blank=True, help_text='Deck to genoa halyard sheave', null=True)),
                ('j', models.FloatField(blank=True, help_text='Foretriangle base', null=True)),
                ('p', models.FloatField(blank=True, help_text='Luff length (mainsail)', null=True)),
                ('mast_height', models.FloatField(blank=True, null=True)),
                ('material', models.CharField(blank=True, choices=[('Aluminum', 'Aluminum'), ('Carbon', 'Carbon'), ('Wood', 'Wood')], max_length=50, null=True)),
                ('base_yacht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masts', to='yachts.baseyacht')),
            ],
        ),
        migrations.CreateModel(
            name='Boom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(blank=True, null=True)),
                ('e', models.FloatField(blank=True, help_text='Aft face of mast to the black band on the boom', null=True)),
                ('material', models.CharField(blank=True, choices=[('Aluminum', 'Aluminum'), ('Carbon', 'Carbon'), ('Wood', 'Wood')], max_length=50, null=True)),
                ('boom_height', models.FloatField(blank=True, null=True)),
                ('boom_type', models.CharField(blank=True, choices=[('Standard', 'Standard'), ('Furling', 'Furling')], max_length=50, null=True)),
                ('base_yacht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booms', to='yachts.baseyacht')),
                ('mast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booms', to='yachts.mast')),
            ],
        ),
        migrations.AddField(
            model_name='baseyacht',
            name='rig_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yachts.rigtype'),
        ),
        migrations.CreateModel(
            name='YachtInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, max_length=200, null=True)),
                ('base_yacht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yachts.baseyacht')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YachtDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_custom_name', models.CharField(blank=True, max_length=200, null=True)),
                ('yacht_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='yachts.yachtinstance')),
            ],
        ),
    ]
