# Generated by Django 5.1.8 on 2025-04-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yachts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boom',
            name='mast',
        ),
        migrations.AddField(
            model_name='boom',
            name='position',
            field=models.CharField(choices=[('main', 'Main Boom'), ('mizzen', 'Mizzen Boom'), ('fore', 'Fore Boom'), ('aft', 'Aft Boom')], default='main', max_length=20),
        ),
    ]
